# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhyfjXWLLiplVFuNFdjEv5si0qs2NDKt
"""

item1 = float(input("Enter the item1 cost: "))
item1_qty =int(input("Enter the quantity of item1: "))
item2 = float(input("Enter the item2 cost: "))
item2_qty =int(input("Enter the quantity of item2: "))
item3 = float(input("Enter the item3 cost: "))
item3_qty =int(input("Enter the quantity of item3: "))
total_item = (item1*item1_qty) + (item2*item2_qty) + (item3*item3_qty)
if total_item > 50:
  total_item = total_item-(total_item*0.10)
  print("Final total cost after 10% discount: ", total_item)
elif total_item==50:
  print("total price is exactly 50, no discount applied: ", total_item)
else:
  print("Total price is below 50, no discount applied: ", total_item)